os: linux
services:
- docker
sudo: required
language: python
env:
  global:
  - CONAN_UPLOAD=1
  - CONAN_REFERENCE="clang/3.8.0"
  - CONAN_USERNAME="smspillaz"
  - CONAN_CHANNEL="stable"
  - CONAN_TOTAL_PAGES=2
  - secure: rhUZ5Xj3C3QLsAEaO5Ezy9PLUCtVHBx7E2Plf4+JykKLnKfaeP2P7oKH+PlNnK9O+G2/sO7VBd8hsQUrVE34nEKfqH9RgV+NUeyT/9IzEdiW2jJrcWVJtfsI2udn5FXQ88NTs84U+EEqWedClOTnhGdkHfv+Owj8FwqdmpKciWv/mBU7DesYbEVxiyVm9xjDfBtF8t8oHvVDcQ1MsUyt3JyFJc0Z78NC28lkquuL0s1Yrwvh/UlzSSRX12Dh2Bdi3Bqu3JHd70x0eF6Jlb8a9QUtVhD8gZ+E1kcex3v0oEkdmIsd0BoDWXabKidukVgoSkqs8TpEtKH2EnLdIwcPzCIwIoZJs3xz1Ykmf0Zqdtbf5EzlpA1yy6qY0buMlrFo0x9F6wLOC/nUFdI2QQiR89zByhjYYakm2QJom0XD1/wtXCcGbpLPOZW6a4GDs6hI5KDYmFumz3CXxpIFfWRr4S9yYEpucpI2nZb3hlNI+/bAJPUF0n0pqWxgQP/VwvYuXFmsmwfSlPJgSk7RVeZ6ZQVDqxKSZip6rPd65JmzAq7aJBdGCg/7QMMDxosyAJGtM69tr4Qmke0hfTx9OxLP8KNbE682/R8dbC5CHyNX/N3cWsZfzSeWCE1r4bIBZuMGCY8oXz1lC6npgdGboo+POvJxlkdUKCXcBHTCVO9XaHY=
  matrix:
  - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1
matrix:
  include:
  - os: osx
    osx_image: xcode7.1
    language: generic
    env: CONAN_CURRENT_PAGE=1
  - os: osx
    osx_image: xcode7.1
    language: generic
    env: CONAN_CURRENT_PAGE=2
  - os: osx
    osx_image: xcode6.4
    language: generic
    env: CONAN_CURRENT_PAGE=1
  - os: osx
    osx_image: xcode6.4
    language: generic
    env: CONAN_CURRENT_PAGE=2
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
